title: "MyCount"
name: "MyCount"
description: "MyCount project documentation."
url: "https://mycount.osoyalce.com"
baseurl: ""
mycount:
  endpoint: "https://count.osoyalce.com/count"
repository: "NadimGhaznavi/mycount"
locale: "en-US"
remote_theme: "NadimGhaznavi/minimal-mistakes"
minimal_mistakes_skin: "dark"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap

author:
  name: "Nadim-Daniel Ghaznavi"
  bio: "Creator"
  location: "Hamilton, ON"
  github: "NadimGhaznavi"
footer:
  since: "2026"

include:
  - pages
exclude:
  - caddy
  - AGENTS.md
  - README.md
  - LICENSE
  - mycount
  - scripts
  - systemd
  - requirements.txt
  - tests
  - vendor
  - .venv

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
