"""Generated by scripts/update-deployment-dependencies.py; edit deployment/rules.json and its template."""

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

from mycount.constants.DControl import DControl
from mycount.constants.DMyCount import DMyCount


class DDeployment:
    RELEASE_MANIFEST: Final[str] = "deployment/releases.json"
    VERSION_MARKER: Final[str] = ".deployment-version"

    REPORT_SERVER: Final[str] = "report-server"
    LISTENER: Final[str] = "listener"
    FILESYSTEM: Final[str] = "filesystem"

    SERVICE_UNITS: Final[Mapping[str, str]] = MappingProxyType({
        REPORT_SERVER: DControl.SERVICE_UNIT,
        LISTENER: DMyCount.SERVICE_UNIT,
    })

    TARGETS: Final[Mapping[str, tuple[str, ...]]] = MappingProxyType({
        "filesystem": (
            "deployment_tools/__main__.py",
            "mycount/activity/DeploymentImpact.py",
            "mycount/activity/ReleaseDeployment.py",
            "mycount/constants/DDeployment.py",
            "scripts/install.sh",
            "scripts/new-release.sh",
            "scripts/uninstall.sh",
            "scripts/update-deployment-dependencies.py",
            "scripts/update-geoip.sh",
            "scripts/upgrade.sh",
        ),
        "listener": (
            "requirements.txt",
            "systemd/mycount-server.service",
        ),
        "report-server": (
            "requirements.txt",
            "systemd/mycount-control.service",
        ),
    })

    DEPENDENCIES: Final[Mapping[str, tuple[str, ...]]] = MappingProxyType({
        "caddy/mycount.caddy": (
        ),
        "deployment/DDeployment.py.in": (
        ),
        "deployment/rules.json": (
            "deployment/DDeployment.py.in",
        ),
        "deployment_tools/DependencyGenerator.py": (
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/DeploymentConfig.py": (
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/DeploymentFiles.py": (
            "deployment_tools/DeploymentConfig.py",
            "deployment_tools/ReleaseFiles.py",
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/DeploymentImpact.py": (
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/ReleaseDeployment.py": (
            "deployment_tools/DeploymentImpact.py",
            "deployment_tools/ReleaseFiles.py",
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/ReleaseFiles.py": (
            "deployment_tools/DeploymentConfig.py",
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/__init__.py": (
        ),
        "deployment_tools/__main__.py": (
            "deployment_tools/DependencyGenerator.py",
            "deployment_tools/__init__.py",
        ),
        "mycount/__init__.py": (
        ),
        "mycount/activity/BrowserMetadata.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DVisitorDetails.py",
            "mycount/entity/Visit.py",
        ),
        "mycount/activity/CollectVisit.py": (
            "mycount/__init__.py",
            "mycount/activity/BrowserMetadata.py",
            "mycount/activity/__init__.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/GeoIp.py",
            "mycount/interface/VisitDb.py",
            "mycount/interface/VisitPayload.py",
        ),
        "mycount/activity/DeploymentImpact.py": (
            "deployment_tools/DeploymentImpact.py",
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DDeployment.py",
        ),
        "mycount/activity/GeoIpSchema.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DGeoIp.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/CountryNameMigration.py",
            "mycount/interface/DbMgr.py",
        ),
        "mycount/activity/ReleaseDeployment.py": (
            "deployment_tools/ReleaseDeployment.py",
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
        ),
        "mycount/activity/UpdateGeoIp.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DGeoIp.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/DatabaseEnvironment.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/GeoIpImportDb.py",
            "mycount/interface/GeoIpSource.py",
        ),
        "mycount/activity/VisitorSchema.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DGeoIp.py",
            "mycount/constants/DMyCount.py",
            "mycount/constants/DVisitorDetails.py",
            "mycount/interface/CountryNameMigration.py",
            "mycount/interface/DbMgr.py",
        ),
        "mycount/activity/__init__.py": (
            "mycount/__init__.py",
        ),
        "mycount/constants/DCaddy.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DControl.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DDbMgr.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DDeployment.py": (
            "mycount/__init__.py",
            "mycount/constants/DControl.py",
            "mycount/constants/DMyCount.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DGeoIp.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DMyCount.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DVisitorDetails.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/__init__.py": (
            "mycount/__init__.py",
        ),
        "mycount/entity/GeoIpRange.py": (
            "mycount/__init__.py",
            "mycount/entity/GeoLocation.py",
            "mycount/entity/__init__.py",
        ),
        "mycount/entity/GeoLocation.py": (
            "mycount/__init__.py",
            "mycount/entity/__init__.py",
        ),
        "mycount/entity/Visit.py": (
            "mycount/__init__.py",
            "mycount/entity/__init__.py",
        ),
        "mycount/entity/__init__.py": (
            "mycount/__init__.py",
        ),
        "mycount/interface/CollectorHttp.py": (
            "mycount/__init__.py",
            "mycount/activity/CollectVisit.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/VisitPayload.py",
            "mycount/interface/VisitorAddress.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/CountryNameMigration.py": (
            "mycount/__init__.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/DatabaseEnvironment.py": (
            "mycount/__init__.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/DbMgr.py": (
            "mycount/__init__.py",
            "mycount/constants/DDbMgr.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/DeploymentConfiguration.py": (
            "deployment_tools/DeploymentConfig.py",
            "mycount/__init__.py",
            "mycount/constants/DDeployment.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/DeploymentFiles.py": (
            "deployment_tools/DeploymentFiles.py",
            "mycount/__init__.py",
            "mycount/interface/DeploymentConfiguration.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/GeoIp.py": (
            "mycount/__init__.py",
            "mycount/entity/GeoLocation.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/GeoIpImportDb.py": (
            "mycount/__init__.py",
            "mycount/constants/DGeoIp.py",
            "mycount/entity/GeoIpRange.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/GeoIpSource.py": (
            "mycount/__init__.py",
            "mycount/constants/DGeoIp.py",
            "mycount/constants/DMyCount.py",
            "mycount/entity/GeoIpRange.py",
            "mycount/entity/GeoLocation.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/ReleaseFiles.py": (
            "deployment_tools/ReleaseFiles.py",
            "mycount/__init__.py",
            "mycount/interface/DeploymentConfiguration.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/ServiceLogger.py": (
            "mycount/__init__.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/VisitDb.py": (
            "mycount/__init__.py",
            "mycount/entity/Visit.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/VisitPayload.py": (
            "mycount/__init__.py",
            "mycount/constants/DMyCount.py",
            "mycount/entity/Visit.py",
            "mycount/interface/VisitorDetails.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/VisitorAddress.py": (
            "mycount/__init__.py",
            "mycount/constants/DCaddy.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/VisitPayload.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/VisitorDetails.py": (
            "mycount/__init__.py",
            "mycount/constants/DVisitorDetails.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/__init__.py": (
            "mycount/__init__.py",
        ),
        "mycount/server/ControlHandler.py": (
            "mycount/__init__.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/VisitDb.py",
            "mycount/server/ControlPages.py",
            "mycount/server/__init__.py",
        ),
        "mycount/server/ControlPages.py": (
            "mycount/__init__.py",
            "mycount/server/__init__.py",
            "mycount/server/templates/control.html",
            "mycount/server/templates/reference.html",
        ),
        "mycount/server/ControlServer.py": (
            "mycount/__init__.py",
            "mycount/constants/DControl.py",
            "mycount/server/ControlHandler.py",
            "mycount/server/__init__.py",
        ),
        "mycount/server/MyCountServer.py": (
            "mycount/__init__.py",
            "mycount/activity/BrowserMetadata.py",
            "mycount/activity/CollectVisit.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/CollectorHttp.py",
            "mycount/interface/ServiceLogger.py",
            "mycount/interface/VisitPayload.py",
            "mycount/server/__init__.py",
        ),
        "mycount/server/__init__.py": (
            "mycount/__init__.py",
        ),
        "mycount/server/__main__.py": (
            "mycount/__init__.py",
            "mycount/server/MyCountServer.py",
            "mycount/server/__init__.py",
        ),
        "mycount/server/templates/base.html": (
            "mycount/server/templates/local_time.html",
            "mycount/server/templates/styles.html",
            "mycount/server/templates/table_sort.html",
        ),
        "mycount/server/templates/control.html": (
            "mycount/server/templates/base.html",
        ),
        "mycount/server/templates/local_time.html": (
        ),
        "mycount/server/templates/reference.html": (
            "mycount/server/templates/base.html",
        ),
        "mycount/server/templates/styles.html": (
        ),
        "mycount/server/templates/table_sort.html": (
        ),
        "requirements.txt": (
        ),
        "scripts/install-caddy.sh": (
            "caddy/mycount.caddy",
            "mycount/constants/DCaddy.py",
            "mycount/constants/DMyCount.py",
        ),
        "scripts/install-services.sh": (
            "mycount/activity/GeoIpSchema.py",
            "mycount/activity/ReleaseDeployment.py",
            "mycount/activity/VisitorSchema.py",
            "mycount/constants/DControl.py",
            "mycount/constants/DDeployment.py",
            "mycount/constants/DGeoIp.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/DatabaseEnvironment.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/DeploymentFiles.py",
            "mycount/interface/ReleaseFiles.py",
            "requirements.txt",
            "scripts/install-caddy.sh",
            "scripts/update-geoip.sh",
        ),
        "scripts/install.sh": (
            "mycount/constants/DDbMgr.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/DatabaseEnvironment.py",
            "scripts/install-services.sh",
        ),
        "scripts/new-release.sh": (
            "mycount/activity/ReleaseDeployment.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/ReleaseFiles.py",
            "scripts/update-deployment-dependencies.py",
        ),
        "scripts/uninstall.sh": (
            "mycount/constants/DCaddy.py",
            "mycount/constants/DControl.py",
            "mycount/constants/DGeoIp.py",
            "mycount/constants/DMyCount.py",
        ),
        "scripts/update-deployment-dependencies.py": (
            "deployment/rules.json",
            "deployment_tools/DependencyGenerator.py",
        ),
        "scripts/update-geoip.sh": (
            "mycount/activity/UpdateGeoIp.py",
        ),
        "scripts/upgrade.sh": (
            "scripts/install-services.sh",
        ),
        "systemd/mycount-control.service": (
            "mycount/constants/DMyCount.py",
            "mycount/server/ControlServer.py",
        ),
        "systemd/mycount-server.service": (
            "mycount/constants/DMyCount.py",
            "mycount/server/__main__.py",
        ),
    })
