"""Generated by scripts/update-deployment-dependencies.py; edit deployment/rules.json and its template."""

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

from mycount.constants.DControl import DControl
from mycount.constants.DMyCount import DMyCount


class DDeployment:
    RELEASE_MANIFEST: Final[str] = "deployment/releases.json"
    VERSION_MARKER: Final[str] = ".deployment-version"

    REPORT_SERVER: Final[str] = "report-server"
    LISTENER: Final[str] = "listener"
    FILESYSTEM: Final[str] = "filesystem"

    SERVICE_UNITS: Final[Mapping[str, str]] = MappingProxyType({
        REPORT_SERVER: DControl.SERVICE_UNIT,
        LISTENER: DMyCount.SERVICE_UNIT,
    })

    TARGETS: Final[Mapping[str, tuple[str, ...]]] = MappingProxyType({
        "filesystem": (
            "deployment_tools/__main__.py",
            "mycount/activity/DeploymentImpact.py",
            "mycount/activity/ReconcileMarketingScreenshots.py",
            "mycount/activity/RefreshCities.py",
            "mycount/activity/ReleaseDeployment.py",
            "mycount/constants/DDeployment.py",
            "scripts/clear-upnpc-routes.sh",
            "scripts/install.sh",
            "scripts/new-release.sh",
            "scripts/uninstall.sh",
            "scripts/update-deployment-dependencies.py",
            "scripts/upgrade.sh",
        ),
        "listener": (
            "requirements.txt",
            "systemd/mycount-router.service",
            "systemd/mycount-server.service",
        ),
        "report-server": (
            "requirements.txt",
            "systemd/mycount-control.service",
        ),
    })

    DEPENDENCIES: Final[Mapping[str, tuple[str, ...]]] = MappingProxyType({
        "caddy/mycount.caddy": (
        ),
        "deployment/DDeployment.py.in": (
        ),
        "deployment/rules.json": (
            "deployment/DDeployment.py.in",
        ),
        "deployment_tools/DependencyGenerator.py": (
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/DeploymentConfig.py": (
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/DeploymentFiles.py": (
            "deployment_tools/DeploymentConfig.py",
            "deployment_tools/ReleaseFiles.py",
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/DeploymentImpact.py": (
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/ReleaseDeployment.py": (
            "deployment_tools/DeploymentImpact.py",
            "deployment_tools/ReleaseFiles.py",
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/ReleaseFiles.py": (
            "deployment_tools/DeploymentConfig.py",
            "deployment_tools/__init__.py",
        ),
        "deployment_tools/__init__.py": (
        ),
        "deployment_tools/__main__.py": (
            "deployment_tools/DependencyGenerator.py",
            "deployment_tools/__init__.py",
        ),
        "mycount/__init__.py": (
        ),
        "mycount/activity/BrowserMetadata.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DVisitorDetails.py",
            "mycount/entity/Visit.py",
        ),
        "mycount/activity/CollectVisit.py": (
            "mycount/__init__.py",
            "mycount/activity/BrowserMetadata.py",
            "mycount/activity/__init__.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/GeoIp.py",
            "mycount/interface/VisitDb.py",
            "mycount/interface/VisitPayload.py",
        ),
        "mycount/activity/CountVisits.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/VisitDb.py",
        ),
        "mycount/activity/DeploymentImpact.py": (
            "deployment_tools/DeploymentImpact.py",
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DDeployment.py",
        ),
        "mycount/activity/MaintainRouterMappings.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DCaddy.py",
            "mycount/constants/DMyCount.py",
            "mycount/constants/DRouterMappings.py",
            "mycount/interface/RouterMappings.py",
        ),
        "mycount/activity/MarketingSchema.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DMarketing.py",
            "mycount/interface/DbMgr.py",
        ),
        "mycount/activity/ReadReports.py": (
            "mycount/__init__.py",
            "mycount/activity/ResolveVisitorLocations.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DReports.py",
            "mycount/entity/Report.py",
            "mycount/entity/ReportOptions.py",
            "mycount/interface/CityLocations.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/MarketingDb.py",
            "mycount/interface/VisitDb.py",
        ),
        "mycount/activity/ReconcileMarketingScreenshots.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/MarketingDb.py",
            "mycount/interface/MarketingScreenshots.py",
        ),
        "mycount/activity/RefreshCities.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/interface/CityLocations.py",
            "mycount/interface/CitySchedule.py",
            "mycount/interface/GeoNamesSource.py",
        ),
        "mycount/activity/ReleaseDeployment.py": (
            "deployment_tools/ReleaseDeployment.py",
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
        ),
        "mycount/activity/ResolveVisitorLocations.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/interface/CityLocations.py",
        ),
        "mycount/activity/SaveMarketingPost.py": (
            "mycount/__init__.py",
            "mycount/activity/__init__.py",
            "mycount/entity/MarketingPost.py",
            "mycount/interface/DbCommitUncertain.py",
            "mycount/interface/MarketingDb.py",
            "mycount/interface/MarketingScreenshots.py",
        ),
        "mycount/activity/VisitorSchema.py": (
            "mycount/__init__.py",
            "mycount/activity/MarketingSchema.py",
            "mycount/activity/__init__.py",
            "mycount/constants/DGeoIp.py",
            "mycount/constants/DMyCount.py",
            "mycount/constants/DVisitorDetails.py",
            "mycount/interface/CountryNameMigration.py",
            "mycount/interface/DbMgr.py",
        ),
        "mycount/activity/__init__.py": (
            "mycount/__init__.py",
        ),
        "mycount/constants/DCaddy.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DCities.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DControl.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DCountryNameMigration.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DDbMgr.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DDeployment.py": (
            "mycount/__init__.py",
            "mycount/constants/DControl.py",
            "mycount/constants/DMyCount.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DGeoIp.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DMarketing.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DMyCount.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DReports.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DRouterMappings.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/DVisitorDetails.py": (
            "mycount/__init__.py",
            "mycount/constants/__init__.py",
        ),
        "mycount/constants/__init__.py": (
            "mycount/__init__.py",
        ),
        "mycount/entity/GeoLocation.py": (
            "mycount/__init__.py",
            "mycount/entity/__init__.py",
        ),
        "mycount/entity/MarketingPost.py": (
            "mycount/__init__.py",
            "mycount/entity/__init__.py",
        ),
        "mycount/entity/Report.py": (
            "mycount/__init__.py",
            "mycount/entity/ReportOptions.py",
            "mycount/entity/__init__.py",
        ),
        "mycount/entity/ReportOptions.py": (
            "mycount/__init__.py",
            "mycount/entity/__init__.py",
        ),
        "mycount/entity/Visit.py": (
            "mycount/__init__.py",
            "mycount/entity/__init__.py",
        ),
        "mycount/entity/__init__.py": (
            "mycount/__init__.py",
        ),
        "mycount/interface/CityLocations.py": (
            "mycount/__init__.py",
            "mycount/constants/DCities.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/CitySchedule.py": (
            "mycount/__init__.py",
            "mycount/constants/DCities.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/CollectorHttp.py": (
            "mycount/__init__.py",
            "mycount/activity/CollectVisit.py",
            "mycount/activity/CountVisits.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/GeoIpUnavailable.py",
            "mycount/interface/VisitPayload.py",
            "mycount/interface/VisitorAddress.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/CountryNameMigration.py": (
            "mycount/__init__.py",
            "mycount/constants/DCountryNameMigration.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/DatabaseEnvironment.py": (
            "mycount/__init__.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/DbCommitUncertain.py": (
            "mycount/__init__.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/DbMgr.py": (
            "mycount/__init__.py",
            "mycount/constants/DDbMgr.py",
            "mycount/interface/DbCommitUncertain.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/DeploymentConfiguration.py": (
            "deployment_tools/DeploymentConfig.py",
            "mycount/__init__.py",
            "mycount/constants/DDeployment.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/DeploymentFiles.py": (
            "deployment_tools/DeploymentFiles.py",
            "mycount/__init__.py",
            "mycount/interface/DeploymentConfiguration.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/GeoIp.py": (
            "mycount/__init__.py",
            "mycount/constants/DGeoIp.py",
            "mycount/constants/DMyCount.py",
            "mycount/entity/GeoLocation.py",
            "mycount/interface/GeoIpUnavailable.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/GeoIpUnavailable.py": (
            "mycount/__init__.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/GeoNamesSource.py": (
            "mycount/__init__.py",
            "mycount/constants/DCities.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/MarketingDb.py": (
            "mycount/__init__.py",
            "mycount/entity/MarketingPost.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/MarketingForm.py": (
            "mycount/__init__.py",
            "mycount/constants/DMarketing.py",
            "mycount/entity/MarketingPost.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/MarketingScreenshots.py": (
            "mycount/__init__.py",
            "mycount/constants/DMarketing.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/MarketingUpload.py": (
            "mycount/__init__.py",
            "mycount/constants/DMarketing.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/ReleaseFiles.py": (
            "deployment_tools/ReleaseFiles.py",
            "mycount/__init__.py",
            "mycount/interface/DeploymentConfiguration.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/ReportQuery.py": (
            "mycount/__init__.py",
            "mycount/constants/DReports.py",
            "mycount/entity/ReportOptions.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/RouterMappings.py": (
            "mycount/__init__.py",
            "mycount/constants/DRouterMappings.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/ServiceLogger.py": (
            "mycount/__init__.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/VisitDb.py": (
            "mycount/__init__.py",
            "mycount/constants/DReports.py",
            "mycount/constants/DVisitorDetails.py",
            "mycount/entity/Visit.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/VisitPayload.py": (
            "mycount/__init__.py",
            "mycount/constants/DMyCount.py",
            "mycount/entity/Visit.py",
            "mycount/interface/VisitorDetails.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/VisitorAddress.py": (
            "mycount/__init__.py",
            "mycount/constants/DCaddy.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/VisitPayload.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/VisitorDetails.py": (
            "mycount/__init__.py",
            "mycount/constants/DVisitorDetails.py",
            "mycount/interface/__init__.py",
        ),
        "mycount/interface/__init__.py": (
            "mycount/__init__.py",
        ),
        "mycount/server/ControlHandler.py": (
            "mycount/__init__.py",
            "mycount/activity/ReadReports.py",
            "mycount/activity/SaveMarketingPost.py",
            "mycount/constants/DMarketing.py",
            "mycount/constants/DMyCount.py",
            "mycount/entity/Report.py",
            "mycount/entity/ReportOptions.py",
            "mycount/interface/CityLocations.py",
            "mycount/interface/CitySchedule.py",
            "mycount/interface/DbCommitUncertain.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/MarketingDb.py",
            "mycount/interface/MarketingForm.py",
            "mycount/interface/MarketingScreenshots.py",
            "mycount/interface/MarketingUpload.py",
            "mycount/interface/ReportQuery.py",
            "mycount/server/ControlPages.py",
            "mycount/server/__init__.py",
        ),
        "mycount/server/ControlPages.py": (
            "mycount/__init__.py",
            "mycount/constants/DMarketing.py",
            "mycount/entity/Report.py",
            "mycount/interface/ReportQuery.py",
            "mycount/server/__init__.py",
            "mycount/server/templates/control.html",
            "mycount/server/templates/marketing.html",
            "mycount/server/templates/reference.html",
            "mycount/server/templates/visitor_map.html",
        ),
        "mycount/server/ControlServer.py": (
            "mycount/__init__.py",
            "mycount/constants/DControl.py",
            "mycount/server/ControlHandler.py",
            "mycount/server/__init__.py",
        ),
        "mycount/server/MyCountServer.py": (
            "mycount/__init__.py",
            "mycount/activity/BrowserMetadata.py",
            "mycount/activity/CollectVisit.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/CollectorHttp.py",
            "mycount/interface/ServiceLogger.py",
            "mycount/interface/VisitPayload.py",
            "mycount/server/__init__.py",
        ),
        "mycount/server/RouterWorker.py": (
            "mycount/__init__.py",
            "mycount/activity/MaintainRouterMappings.py",
            "mycount/interface/RouterMappings.py",
            "mycount/server/__init__.py",
        ),
        "mycount/server/__init__.py": (
            "mycount/__init__.py",
        ),
        "mycount/server/__main__.py": (
            "mycount/__init__.py",
            "mycount/server/MyCountServer.py",
            "mycount/server/__init__.py",
        ),
        "mycount/server/templates/all_traffic.html": (
        ),
        "mycount/server/templates/base.html": (
            "mycount/server/templates/local_time.html",
            "mycount/server/templates/styles.html",
            "mycount/server/templates/table_sort.html",
        ),
        "mycount/server/templates/chart_theme.html": (
        ),
        "mycount/server/templates/city_schedule.html": (
        ),
        "mycount/server/templates/control.html": (
            "mycount/server/templates/all_traffic.html",
            "mycount/server/templates/base.html",
            "mycount/server/templates/chart_theme.html",
            "mycount/server/templates/pie_charts.html",
            "mycount/server/templates/report_filters.html",
        ),
        "mycount/server/templates/local_time.html": (
        ),
        "mycount/server/templates/marketing.html": (
            "mycount/server/templates/base.html",
            "mycount/server/templates/chart_theme.html",
            "mycount/server/templates/marketing_chart.html",
            "mycount/server/templates/marketing_form.html",
            "mycount/server/templates/report_filters.html",
        ),
        "mycount/server/templates/marketing_chart.html": (
        ),
        "mycount/server/templates/marketing_form.html": (
        ),
        "mycount/server/templates/pie_charts.html": (
        ),
        "mycount/server/templates/reference.html": (
            "mycount/server/templates/base.html",
        ),
        "mycount/server/templates/report_filters.html": (
        ),
        "mycount/server/templates/styles.html": (
        ),
        "mycount/server/templates/table_sort.html": (
        ),
        "mycount/server/templates/visitor_map.html": (
            "mycount/server/templates/base.html",
            "mycount/server/templates/city_schedule.html",
            "mycount/server/templates/report_filters.html",
        ),
        "requirements.txt": (
        ),
        "scripts/clear-upnpc-routes.sh": (
            "mycount/constants/DCaddy.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/RouterMappings.py",
        ),
        "scripts/install-caddy.sh": (
            "caddy/mycount.caddy",
            "mycount/constants/DCaddy.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/RouterMappings.py",
        ),
        "scripts/install-services.sh": (
            "mycount/activity/ReleaseDeployment.py",
            "mycount/activity/VisitorSchema.py",
            "mycount/constants/DCities.py",
            "mycount/constants/DControl.py",
            "mycount/constants/DDeployment.py",
            "mycount/constants/DGeoIp.py",
            "mycount/constants/DMyCount.py",
            "mycount/constants/DRouterMappings.py",
            "mycount/interface/CitySchedule.py",
            "mycount/interface/DatabaseEnvironment.py",
            "mycount/interface/DbMgr.py",
            "mycount/interface/DeploymentFiles.py",
            "mycount/interface/ReleaseFiles.py",
            "requirements.txt",
            "scripts/install-caddy.sh",
        ),
        "scripts/install.sh": (
            "mycount/constants/DDbMgr.py",
            "mycount/constants/DMyCount.py",
            "mycount/interface/DatabaseEnvironment.py",
            "scripts/install-services.sh",
        ),
        "scripts/new-release.sh": (
            "mycount/activity/ReleaseDeployment.py",
            "mycount/interface/ReleaseFiles.py",
            "scripts/update-deployment-dependencies.py",
        ),
        "scripts/uninstall.sh": (
            "mycount/constants/DCaddy.py",
            "mycount/constants/DCities.py",
            "mycount/constants/DControl.py",
            "mycount/constants/DGeoIp.py",
            "mycount/constants/DMarketing.py",
            "mycount/constants/DMyCount.py",
            "mycount/constants/DRouterMappings.py",
        ),
        "scripts/update-deployment-dependencies.py": (
            "deployment/rules.json",
            "deployment_tools/DependencyGenerator.py",
        ),
        "scripts/upgrade.sh": (
            "scripts/install-services.sh",
        ),
        "systemd/mycount-control.service": (
            "mycount/constants/DMyCount.py",
            "mycount/server/ControlServer.py",
        ),
        "systemd/mycount-router.service": (
            "mycount/constants/DMyCount.py",
            "mycount/server/RouterWorker.py",
        ),
        "systemd/mycount-server.service": (
            "mycount/constants/DMyCount.py",
            "mycount/server/__main__.py",
        ),
    })
